### ISSUE TITLE
Update workflows

### ISSUE THREAD

**Issue by JaGeo** [JaGeo/LobsterPy#108]
**Describe the bug**
Tests seem to fail. They worked for the pull request but failed afterwards, @naik-aakash .

**Comment by naik-aakash** [comment]
Hi Janine, thanks for this issue. So I think the problem is Black is not in pylint workflow, but I have added this check in pre-commit config. If pre-commit is used before pushing any commits, this should not happen in the future. Maybe I can write this in the README file as well on how to contribute. 

I will add black runs in the pylint workflow as well and raise a PR for the updated pylint workflow. Sorry for the inconvenience

**Comment by JaGeo** [comment]
Could you make the precommit part of the workflow so that we don't run into this issue anymore?

**Comment by naik-aakash** [comment]
Sure. I will have a look at how to do it. Should be fairly quick, I think

**Comment by naik-aakash** [comment]
Btw, and I am not sure why Pylint did not run on the PR raised in first place. It just seems to have run only the test workflow. Pylint runs for me always on each commit first and I see if any of the linting fails on my repo. Very confused 😕
